services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - ./conf/init.sql:/docker-entrypoint-initdb.d/init.sql:z
      # - ./postgres.conf:/etc/postgresql/postgresql.conf:z
