up: down
	pkgx docker-compose up -d

down:
	pkgx docker-compose down

run: up
	#!/usr/bin/env -S bash -x
	echo "Creating partitioned table"
	scripts/run.sh replace 1 2024-02-10
	scripts/run.sh replace 1 2024-02-11
	scripts/run.sh replace 1 2024-02-12
	scripts/run.sh replace 1 2024-02-13
	scripts/run.sh replace 1 2024-02-14
	scripts/run.sh replace 1 2024-02-15
	scripts/run.sh replace 1 2024-02-16
	scripts/run.sh replace 1 2024-02-17
	scripts/run.sh replace 1 2024-02-18
	scripts/run.sh replace 1 2024-02-19

	scripts/run.sh replace 1 2025-02-10
	scripts/run.sh replace 1 2025-02-11
	scripts/run.sh replace 1 2025-02-12
	scripts/run.sh replace 1 2025-02-13
	scripts/run.sh replace 1 2025-02-14
	scripts/run.sh replace 1 2025-02-15
	scripts/run.sh replace 1 2025-02-16
	scripts/run.sh replace 1 2025-02-17
	scripts/run.sh replace 1 2025-02-18
	scripts/run.sh replace 1 2025-02-19

partitioned:
	cd conf; ln -sf ./partitioned.sql ./init.sql
	just up
	just run > partitioned.log


non-partitioned:
	cd conf; ln -sf ./non-partitioned.sql ./init.sql
	just up
	just run > non-partitioned.log
